induction c with d hd generalizing b,
intro h1,
rw mul_zero at h1,
rw mul_eq_zero_iff at h1,
cases h1 with h2 h3,
exfalso,
exact ha(h2),

exact h3,

intro g1,
cases b,
rw mul_zero at g1,
symmetry at g1,
rw mul_eq_zero_iff a (succ d) at g1,
cases g1,
exfalso,
have g2 := ha(g1),
exact g2,

symmetry at g1,
exact g1,

repeat {rw mul_succ at g1},
rw add_right_cancel_iff at g1,
have g2 := hd(b),
have g3:= g2(g1),
have g4:= succ_eq_succ_of_eq g3,
exact g4,