intro h,
rw succ_eq_add_one at h,
rw ← add_zero n at h,
rw add_assoc at h,
rw zero_add at h,
have h1:= add_left_cancel n 0 1,
have h2:= h1(h),
rw one_eq_succ_zero at h2,
have h3:= zero_ne_succ 0,
apply h3(h2),