intro h,
cases h with c h1,
rw succ_add at h1,
rw add_comm at h1,
rw ← succ_add at h1,
rw add_comm at h1,
symmetry at h1,
have p1 := eq_zero_of_add_right_eq_self h1,
have p2 := succ_ne_zero c,
exact p2 p1,