cases hba with d p,
cases hab with e q,
rw q at p,
rw add_assoc at p,
symmetry at p,
have r := eq_zero_of_add_right_eq_self p,
have s := add_right_eq_zero r,
rw s at q,
rw add_zero at q,
symmetry at q,
exact q,