induction n with k hk,
rw pow_zero,
rw pow_zero,
rw pow_zero,
rw mul_one,
refl,

rw pow_succ a k,
rw pow_succ b k,
rw pow_succ,
rw hk,
rw mul_assoc (a^k) a ((b^k)*b),
rw ← mul_left_comm (b^k) a b,
rw ← mul_assoc (a^k) (b^k) (a*b),
refl,