rw two_eq_succ_one,
rw one_eq_succ_zero,
repeat {rw pow_succ},
repeat {rw pow_zero},
repeat {rw one_mul},
repeat {rw succ_mul},
rw zero_mul,
rw zero_add,
repeat {rw add_mul},
repeat {rw mul_add},
rw add_right_comm (a*a) (a*b) ((b*a)+(b*b)),
rw add_comm (b*a) (b*b),
rw ← add_assoc (a*a) (b*b) (b*a),
rw mul_comm b a,
rw ← add_assoc ((a*a)+(b*b)) (a*b) (a*b),
refl,