induction t with u hu,
rw mul_zero,
rw mul_zero,
rw mul_zero,
rw add_zero,
refl,

rw mul_succ (a+b) u,
rw mul_succ a u,
rw mul_succ b u,
rw hu,
rw add_right_comm (a*u) a (b*u+b),
rw add_assoc (a*u) (b*u + b) a,
rw add_right_comm (b*u) b a,
rw ← add_assoc (a*u) (b*u+a) b,
rw ← add_assoc (a*u) (b*u) a,
rw ← add_assoc(a*u +b*u) a b,
refl,